version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          command: pip install pytest mypy pyright
      - run:
          command: uvx ruff check
      - run:
          command: pyright
      - run:
          command: mypy **/*.py
      - run:
          command: pytest
          environment:
            FORCE_COLOR: 1 # pytest の出力が白黒にならないようにする
