version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.13
    environment:
      FORCE_COLOR: 1 # 出力が白黒にならないようにする
    steps:
      - checkout
      - run:
          command: pip install pytest mypy pyright
      - run:
          command: uvx ruff check
      # - run:
      #     command: uvx ruff format --check --diff
      - run:
          command: pyright
      - run:
          command: mypy **/*.py
      - run:
          command: pytest
