version: 2

jobs:
  ruff:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          command: uvx ruff check
      # - run:
      #     command: uvx ruff format --check --diff

  test:
    docker:
      - image: cimg/python:3.13
    environment:
      FORCE_COLOR: 1 # 出力が白黒にならないようにする
    steps:
      - checkout
      - run:
          command: pip install pytest pytest-cov mypy pyright
      - run:
          command: pyright
      - run:
          command: mypy **/*.py
      - run:
          command: pytest --cov --cov-branch

workflows:
  version: 2
  ruff_and_test:
    jobs:
      - ruff
      - test
